"""
    This is a script that takes all of the intermediate parquet files that are generated by previous rules
    and combines them into a single duckdb
"""
import argparse
import duckdb
import pandas as pd

from utils.DatabaseTools.ValuesDB_V110 import InitializeValuesDatabaseV110
from utils.annotate_well_genes import annotate_well_genes



def combine_parquets(
    parquets_path: str, 
    output: str,
    manifest: str,
    library_annotation_file: str,
    ):
    
    
    InitializeValuesDatabaseV110(output)
    con = duckdb.connect(output, read_only=False)
    
#CREATE AND WRITE FOVs TABLE  
    manifest_df = pd.read_csv(manifest)
    FOVs_df = annotate_well_genes(library_annotation_file, manifest_df)
    
    con.execute("""
        INSERT INTO FOVs (
            plate_id,
            well_row,
            well_column,
            well_site,
            well_type,
            plate_name,
            acquisition_date,
            plate_number,
            marker_symbol,
            mgi_gene_id,
            entrez_id,
            gene_product
        )
        SELECT
            plate_id,
            well_row,
            well_column,
            well_site,
            well_type,
            plate_name,
            acquisition_date,
            plate_number,
            marker_symbol,
            mgi_gene_id,
            entrez_id,
            gene_product
        FROM
            FOVs_df
    """)
    
#WRITE CELLS TABLE
    con.execute(f"""
        INSERT INTO cells (
            plate_id,
            well_row,
            well_column,
            well_site,
            cell_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity
        )
        SELECT
            plate_id,
            well_row,
            well_column,
            well_site,
            cell_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity
        FROM '{parquets_path}/*_cellpose.parquet'   
        """)
    
    

# WRITE CONSTITUTIVE TABLE
    con.execute(f"""
        INSERT into constitutive (
            plate_id,
            well_row,
            well_column,
            well_site,
            constitutive_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        )
        SELECT
            plate_id,
            well_row,
            well_column,
            well_site,
            constitutive_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        FROM '{parquets_path}/*_constitutive.parquet'            
    """)

# WRITE REPORTER TABLE
    con.execute(f"""
        INSERT into reporter (
            plate_id,
            well_row,
            well_column,
            well_site,
            reporter_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        )
        SELECT
            plate_id,
            well_row,
            well_column,
            well_site,
            reporter_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        FROM '{parquets_path}/*_reporter.parquet'            
    """)

#WRITE CONSTITUTIVE OVERLAP TABLE
    con.execute(f"""
            INSERT into cell_bac_overlaps (
                plate_id,
                well_row,
                well_column,
                well_site,
                const_overlap_id,
                cell_id,
                constitutive_id,
                area,
                centroid_0,
                centroid_1,
                eccentricity,
                intensity_mean_0,
                intensity_mean_1,
                intensity_max_0,
                intensity_max_1,
                intensity_min_0,
                intensity_min_1,
                intensity_std_0,
                intensity_std_1,
                length
            )
            SELECT
                plate_id,
                well_row,
                well_column,
                well_site,
                const_overlap_id,
                cell_id,
                constitutive_id,
                area,
                centroid_0,
                centroid_1,
                eccentricity,
                intensity_mean_0,
                intensity_mean_1,
                intensity_max_0,
                intensity_max_1,
                intensity_min_0,
                intensity_min_1,
                intensity_std_0,
                intensity_std_1,
                length
            FROM '{parquets_path}/*_constOverlap.parquet'            
        """)

# WRITE REPORTER OVERLAP TABLE
    # con.execute(f"""
    #         INSERT into reporter_overlaps (
    #             plate_id,
    #             well_row,
    #             well_column,
    #             well_site,
    #             rep_overlap_id,
    #             reporter_id,
    #             const_overlap_id,
    #             area,
    #             centroid_0,
    #             centroid_1,
    #             eccentricity,
    #             intensity_mean_0,
    #             intensity_mean_1,
    #             intensity_max_0,
    #             intensity_max_1,
    #             intensity_min_0,
    #             intensity_min_1,
    #             intensity_std_0,
    #             intensity_std_1,
    #             length
    #         )
    #         SELECT
    #             plate_id,
    #             well_row,
    #             well_column,
    #             well_site,
    #             rep_overlap_id,
    #             reporter_id,
    #             const_overlap_id,
    #             area,
    #             centroid_0,
    #             centroid_1,
    #             eccentricity,
    #             intensity_mean_0,
    #             intensity_mean_1,
    #             intensity_max_0,
    #             intensity_max_1,
    #             intensity_min_0,
    #             intensity_min_1,
    #             intensity_std_0,
    #             intensity_std_1,
    #             length
    #         FROM '{parquets_path}/*_repOverlap.parquet'            
    #     """)

    con.commit()

def main():
    #First, load relevant parameters from argv
    parser = argparse.ArgumentParser()
    parser.add_argument('--parquets_path', '-p', help="Path to intermediate parquet files", type=str)
    parser.add_argument('--output', '-o', help="Path to output duckdb file", type=str)
    parser.add_argument('--manifest', help="Path to the manifest.csv file", type=str, default='./manifest.csv')
    parser.add_argument('--library_annotation_file', help="Path to a .csv file with library annotations", type=str)

    
    args = vars(parser.parse_args())
    
    combine_parquets(args['parquets_path'], args['output'], args['manifest'], args['library_annotation_file'])
    
if __name__ == "__main__":
    main()
    #combine_parquets('Test_Output/AVI0G830_TestPlate/parquet', 'Test_Output/test.db', 'Test_Output/AVI0G830_TestPlate/manifest.csv', '/Users/owenburroughs/Desktop/Personal_Skaar_Lab/EPS007_Code/BacilliScope/SangerLibraryAnnotations.csv')