"""
    This is a script that takes all of the intermediate parquet files that are generated by previous rules
    and combines them into a single duckdb
"""
import argparse
import datetime as dt

import duckdb
import pandas as pd

from utils.ValuesDB_V110 import InitializeValuesDatabaseV110

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from snakemake.iocontainers import snakemake

# ---------------------------------------
# POPULATE THE FOVs TABLE
# ---------------------------------------
def populate_FOVs_df(
    represented_FOVs: list,
    plate_name: str,
    plate_number: int,
    acquisition_date: str,
    
    control_virus_wells: list,
    reporter_control_wells: list,
    uninfected_wells: list,
    
    library_annotation_file: str
    
)-> pd.DataFrame:
    
    # First, establish the dataframe with all of the FOVs represented here
    FOVs_df = pd.DataFrame.from_dict(represented_FOVs)
    
    # Add run metadata
    FOVs_df['plate_name'] = plate_name
    FOVs_df['plate_number'] = plate_number
    FOVs_df['well_type'] = 'gene_target'
    FOVs_df['acquisition_date'] = dt.date.fromisoformat(acquisition_date)
    
    # Add control virus wells
    for well_row, well_column in control_virus_wells:
        mask = (
            (FOVs_df['well_row'] == well_row) &
            (FOVs_df['well_column'] == well_column)
        )
        FOVs_df.loc[mask, 'well_type'] = 'control_virus'
            
    # Add reporter control wells
    for well_row, well_column in reporter_control_wells:
        mask = (
            (FOVs_df['well_row'] == well_row) &
            (FOVs_df['well_column'] == well_column)
        )
        FOVs_df.loc[mask, 'well_type'] = 'reporter_control'
    
    # Add uninfected wells
    for well_row, well_column in uninfected_wells:
        mask = (
            (FOVs_df['well_row'] == well_row) &
            (FOVs_df['well_column'] == well_column)
        )
        FOVs_df.loc[mask, 'well_type'] = 'uninfected'
        
    # Set the datatypes so they match the annotation dataframe
    FOVs_df = FOVs_df.astype({
        "plate_number" : "int64",
        "well_column" : "int64",
        "well_row" : "str"
    })
    
    # Annotate the dataframe with the well genes
    library_annotation_df = pd.read_csv(library_annotation_file)
    FOVs_df = FOVs_df.merge(library_annotation_df, how='left', on=['plate_number', 'well_row', 'well_column'])
    
    return FOVs_df


# ---------------------------------------
# COMBINE PARQUETS INTO DUCKDB
# ---------------------------------------
def combine_parquets(
    cellpose_parquets: list,
    constitutive_parquets: list,
    reporter_parquets: list,
    constOverlap_parquets: list,
    repOverlap_parquets: list,
    database_output: str,
    FOVs_df: pd.DataFrame
    ):
    
    
    InitializeValuesDatabaseV110(database_output)
    con = duckdb.connect(database_output, read_only=False)
    
    con.execute("""
        INSERT INTO FOVs (
            well_row,
            well_column,
            well_site,
            well_type,
            plate_name,
            acquisition_date,
            plate_number,
            marker_symbol,
            mgi_gene_id,
            entrez_id,
            gene_product
        )
        SELECT
            well_row,
            well_column,
            well_site,
            well_type,
            plate_name,
            acquisition_date,
            plate_number,
            marker_symbol,
            mgi_gene_id,
            entrez_id,
            gene_product
        FROM
            FOVs_df
    """)
    
#WRITE CELLS TABLE
    con.execute(f"""
        INSERT INTO cells (
            plate_name,
            well_row,
            well_column,
            well_site,
            cell_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity
        )
        SELECT
            plate_name,
            well_row,
            well_column,
            well_site,
            cell_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity
        FROM read_parquet(?)  
        """, [cellpose_parquets])
    
    

# WRITE CONSTITUTIVE TABLE
    con.execute(f"""
        INSERT into constitutive (
            plate_name,
            well_row,
            well_column,
            well_site,
            constitutive_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        )
        SELECT
            plate_name,
            well_row,
            well_column,
            well_site,
            constitutive_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        FROM read_parquet(?)            
    """, [constitutive_parquets])

# WRITE REPORTER TABLE
    con.execute(f"""
        INSERT into reporter (
            plate_name,
            well_row,
            well_column,
            well_site,
            reporter_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        )
        SELECT
            plate_name,
            well_row,
            well_column,
            well_site,
            reporter_id,
            area,
            centroid_0,
            centroid_1,
            eccentricity,
            intensity_mean_0,
            intensity_mean_1,
            intensity_max_0,
            intensity_max_1,
            intensity_min_0,
            intensity_min_1,
            intensity_std_0,
            intensity_std_1,
            length
        FROM read_parquet(?)            
    """, [reporter_parquets])

#WRITE CONSTITUTIVE OVERLAP TABLE
    con.execute(f"""
            INSERT into cell_bac_overlaps (
                plate_name,
                well_row,
                well_column,
                well_site,
                const_overlap_id,
                cell_id,
                constitutive_id,
                area,
                centroid_0,
                centroid_1,
                eccentricity,
                intensity_mean_0,
                intensity_mean_1,
                intensity_max_0,
                intensity_max_1,
                intensity_min_0,
                intensity_min_1,
                intensity_std_0,
                intensity_std_1,
                length
            )
            SELECT
                plate_name,
                well_row,
                well_column,
                well_site,
                const_overlap_id,
                cell_id,
                constitutive_id,
                area,
                centroid_0,
                centroid_1,
                eccentricity,
                intensity_mean_0,
                intensity_mean_1,
                intensity_max_0,
                intensity_max_1,
                intensity_min_0,
                intensity_min_1,
                intensity_std_0,
                intensity_std_1,
                length
            FROM read_parquet(?)            
        """, [constOverlap_parquets])

# WRITE REPORTER OVERLAP TABLE
    # con.execute(f"""
    #         INSERT into reporter_overlaps (
    #             plate_name,
    #             well_row,
    #             well_column,
    #             well_site,
    #             rep_overlap_id,
    #             reporter_id,
    #             const_overlap_id,
    #             area,
    #             centroid_0,
    #             centroid_1,
    #             eccentricity,
    #             intensity_mean_0,
    #             intensity_mean_1,
    #             intensity_max_0,
    #             intensity_max_1,
    #             intensity_min_0,
    #             intensity_min_1,
    #             intensity_std_0,
    #             intensity_std_1,
    #             length
    #         )
    #         SELECT
    #             plate_name,
    #             well_row,
    #             well_column,
    #             well_site,
    #             rep_overlap_id,
    #             reporter_id,
    #             const_overlap_id,
    #             area,
    #             centroid_0,
    #             centroid_1,
    #             eccentricity,
    #             intensity_mean_0,
    #             intensity_mean_1,
    #             intensity_max_0,
    #             intensity_max_1,
    #             intensity_min_0,
    #             intensity_min_1,
    #             intensity_std_0,
    #             intensity_std_1,
    #             length
    #         FROM read_parquet(?)           
    #     """, [repOverlap_parquets])

    con.commit()

    
if __name__ == "__main__":
    
    # Load parameters for populating metadata
    represented_FOVs = snakemake.params['represented_FOVs']
    plate_name = snakemake.params['plate_name']
    plate_number = snakemake.params['plate_number']
    acquisition_date = snakemake.params['acquisition_date']
    control_virus_wells = snakemake.params['control_virus_wells']
    reporter_control_wells = snakemake.params['reporter_control_wells']
    uninfected_wells = snakemake.params['uninfected_wells']
    library_annotation_file = snakemake.input['library_annotation_file']
    
    # Load the input/output files we need
    cellpose_parquets = snakemake.input['cellpose_parquets']
    constitutive_parquets = snakemake.input['constitutive_parquets']
    reporter_parquets = snakemake.input['reporter_parquets']
    constOverlap_parquets = snakemake.input['constOverlap_parquets']
    repOverlap_parquets = snakemake.input['repOverlap_parquets']
    database_output = snakemake.output['database_output']
    
    # Populate the FOV metadata table
    FOVs_df = populate_FOVs_df(
        represented_FOVs= represented_FOVs,
        plate_name= plate_name,
        plate_number= plate_number,
        acquisition_date= acquisition_date,
        control_virus_wells= control_virus_wells,
        reporter_control_wells= reporter_control_wells,
        uninfected_wells= uninfected_wells,
        library_annotation_file= library_annotation_file
    )
    
    combine_parquets(
        cellpose_parquets= cellpose_parquets,
        constitutive_parquets= constitutive_parquets,
        reporter_parquets= reporter_parquets,
        constOverlap_parquets= constOverlap_parquets,
        repOverlap_parquets= repOverlap_parquets,
        database_output= database_output,
        FOVs_df= FOVs_df
    )
# def main():
#     #First, load relevant parameters from argv
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--parquets_path', '-p', help="Path to intermediate parquet files", type=str)
#     parser.add_argument('--output', '-o', help="Path to output duckdb file", type=str)
#     parser.add_argument('--manifest', help="Path to the manifest.csv file", type=str, default='./manifest.csv')
#     parser.add_argument('--library_annotation_file', help="Path to a .csv file with library annotations", type=str)

    
#     args = vars(parser.parse_args())
    
#     combine_parquets(args['parquets_path'], args['output'], args['manifest'], args['library_annotation_file'])