#Import requirements
import os
import duckdb

def InitializeValuesDatabaseV100(
        db_path: str, 
        remove_existing: bool = True,
        db_name: str = None,
        create_ART_indexes: bool = False
        ) -> None:

    '''
        Initializes the valuesdatabase schema for Bacilliscope using schema version 1.0.0.
        The values database is designed to store quantitative measurements extracted from images, as opposed to databases that store raw images or metadata about the plates.
        
        NOTE: Schema version 1.0.0 is NOT stable. It is subject to change as new features are added.
        Internal compatibility is NOT guaranteed between versions. Use at your own risk.
        
        Parameters:
            db_path (str): Path to the DuckDB database file.
            remove_existing (bool): If True, removes existing database file before initialization.
            db_name (str): Optional name for the database. If None, uses the file name.
            
        Returns:
            None
    '''

    #remove the database file if requested by the user
    if remove_existing:
        print("Removing existing")
        if os.path.exists(db_path):
            os.remove(db_path)
        if os.path.exists(db_path + ".wal"):
            os.remove(db_path + ".wal")
            
    #if a database name is not provided, use the file name as default
    if db_name is None:
        db_name = os.path.basename(db_path)

    # Ensure directory exists
    directory = os.path.dirname(db_path)
    if directory and not os.path.exists(directory):
        os.makedirs(directory, exist_ok=True)
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        
    #connect to the database
    con = duckdb.connect(db_path, read_only=False)
    try:    
    # ---- METADATA TABLE ----
        '''
            The metadata table MUST contain a 'schema_version' key to indicate the version of the schema used.
            Additional metadata can be added as needed. Which metadata is required is based on the schema version
        '''
        
        con.execute(f"""
        CREATE TABLE IF NOT EXISTS __meta__ (
            key TEXT PRIMARY KEY,
            value JSON
        );
        """)
        
        con.execute(f"""
        INSERT INTO __meta__ (key, value) VALUES
            ('schema_version', '"1_0_0"'),
            ('database_name', '"{db_name}"'),
            ('created_at', current_timestamp)
        """)
        
    # ---- SEQUENCES TABLE ----
        con.execute("CREATE SEQUENCE IF NOT EXISTS roi_id_seq START 1;")
        con.execute("CREATE SEQUENCE IF NOT EXISTS cell_id_seq START 1;")
        con.execute("CREATE SEQUENCE IF NOT EXISTS bacteria_id_seq START 1;")
        con.execute("CREATE SEQUENCE IF NOT EXISTS overlap_id_seq START 1;")

    # ---- ROIs TABLE ----
        con.execute("""
        CREATE TABLE IF NOT EXISTS ROIs (
            roi_id  BIGINT PRIMARY KEY DEFAULT nextval('roi_id_seq'),
            well_site INTEGER, --auto-generated
            plate_name  VARCHAR, --this is provided by the user
            acquisition_date TIMESTAMP, --auto-generated
            plate_number INTEGER, --corresponds to the number of the physical plate in the library, used for gene lookup
            well_row     CHAR(1), --provided by the user
            well_column INTEGER, --provided by the user
            update_timestamp TIMESTAMP --This lets me pre-populate this table without worrying about errors later from incomplete runs
        );
        """)
        print("made ROIs table")

    # ---- CELLS TABLE ----
        con.execute("""
        CREATE TABLE IF NOT EXISTS cells (
            cell_id     BIGINT PRIMARY KEY DEFAULT nextval('cell_id_seq'),
            roi_id      BIGINT NOT NULL REFERENCES ROIs(roi_id),
            area        DOUBLE, --from skimage
            centroid_0  DOUBLE, --from skimage, X value of centroid
            centroid_1  DOUBLE, --from skimage, Y value of centroid
            eccentricity    DOUBLE, --from skimage
            label  INT, --the label of the cell as generated by cellpose/skimage. For reproducibility.
        );
        """)

    # ---- BACTERIA TABLE----
        con.execute("""
        CREATE TABLE IF NOT EXISTS bacteria (
            bacteria_id  BIGINT PRIMARY KEY DEFAULT nextval('bacteria_id_seq'),
            roi_id BIGINT NOT NULL REFERENCES ROIs(roi_id),
            area  DOUBLE, -- area of the segnemted region
            label INT, -- the internal label assigned by skimage
            centroid_0 DOUBLE, -- X coordinate of centroid
            centroid_1  DOUBLE, -- Y coordinate of centroid
            eccentricity DOUBLE, -- eccentricity of the segmented region
            intensity_mean_0 DOUBLE, -- mean intensity in the segmented region for constitutive channel
            intensity_mean_1 DOUBLE, -- mean intensity in the segmented region for reporter channel
            intensity_max_0  DOUBLE, -- max in the constitutive channel
            intensity_max_1 DOUBLE, -- max in the reporter channel
            intensity_min_0 DOUBLE, -- min in the constitutive channel
            intensity_min_1 DOUBLE, -- min in the reporter channel
            intensity_std_0 DOUBLE, -- std dev in the constitutive channel
            intensity_std_1 DOUBLE, -- std dev in the reporter channel
            length DOUBLE -- this is actually an integer now, but keeping as double for forwards compatibility
        );
        """)

    # ---- OVERLAPS TABLE----
        con.execute("""
        CREATE TABLE IF NOT EXISTS cell_bac_overlaps (
            overlap_id   BIGINT PRIMARY KEY DEFAULT nextval('overlap_id_seq'),
            cell_id      BIGINT NOT NULL REFERENCES cells(cell_id),
            bacteria_id  BIGINT NOT NULL REFERENCES bacteria(bacteria_id),
            roi_id BIGINT NOT NULL REFERENCES ROIs(roi_id),
            area  DOUBLE, -- area of the segnemted region
            label INT, -- the internal label assigned by skimage
            centroid_0 DOUBLE, -- X coordinate of centroid
            centroid_1  DOUBLE, -- Y coordinate of centroid
            eccentricity DOUBLE, -- eccentricity of the segmented region
            intensity_mean_0 DOUBLE, -- mean intensity in the segmented region for constitutive channel
            intensity_mean_1 DOUBLE, -- mean intensity in the segmented region for reporter channel
            intensity_max_0  DOUBLE, -- max in the constitutive channel
            intensity_max_1 DOUBLE, -- max in the reporter channel
            intensity_min_0 DOUBLE, -- min in the constitutive channel
            intensity_min_1 DOUBLE, -- min in the reporter channel
            intensity_std_0 DOUBLE, -- std dev in the constitutive channel
            intensity_std_1 DOUBLE, -- std dev in the reporter channel
            length DOUBLE -- this is actually an integer now, but keeping as double for forwards compatibility
        );
        """)

    # ---- INDEXES (if requested by user) ----
        if create_ART_indexes:
            con.execute("CREATE INDEX IF NOT EXISTS idx_cells_roi_id     ON cells(roi_id);")
            con.execute("CREATE INDEX IF NOT EXISTS idx_bacteria_roi_id  ON bacteria(roi_id);")
            con.execute("CREATE INDEX IF NOT EXISTS idx_overlap_cell      ON cell_bac_overlaps(cell_id);")
            con.execute("CREATE INDEX IF NOT EXISTS idx_overlap_bacteria  ON cell_bac_overlaps(bacteria_id);")
        
        # Commit all changes to ensure they're persisted
        con.commit()
        print("Schema initialized successfully.")
        
        print(con.execute("SHOW TABLES").fetchall())
        
    except Exception as e:
        print(f"ERROR: {type(e).__name__}: {e}")
        raise
    finally:
        con.close()
        print("Database connection closed.")

    
